### ISSUE TITLE
ORB_SLAM2编译

### ISSUE THREAD

**Issue by gfall-1407** [YabinXuTUD/HRBFFusion3D#3]
麻烦问一下在编译Core时，需要先编译ORBSLAM2么？在src下有FindORBSLAM2.cmake，但是在ORB_SLAM2_m的cmake_modules下又有Findhrbffusion.cmake。

**Comment by gfall-1407** [comment]
请问这是不是循环依赖啊

**Comment by zouhongwei** [comment]
Hi, do you compile the project successful?

**Comment by gfall-1407** [comment]
> Hi, do you compile the project successful?

Yes, but in Windows, Visual Studio2019
